In [2]:
import pandas as pd
import scipy

from eval_functions import compute_bootstrap, print_bootstrap_results, get_score, do_t_test

In [3]:
test_1 = pd.read_csv("/Users/chandlershortlidge/Desktop/Ironhack/fitness-form-coach/llm-evals/variance_test_data/test01-variance-test-baseline.csv")
test_1.head()

,id,inputs,reference_outputs,session_name,repetition,outputs,run,status,error,latency,tokens,total_cost,correctness,hallucination
0,1356d8bf-56fd-4340-a5c6-33a7bc113ae8,"{""user_query"": ""How's my form?""}","{""answer"": ""Bar path shifts forward and backwa...",variance-test-baseline-0e00f0d1,1,"{""answer"": ""Nice work — this looks like a soli...","{""inputs"": {""user_query"": ""How's my form?""}, ""...",success,NaN,13.422553,9588,0.022548,1.0,1.0
1,1356d8bf-56fd-4340-a5c6-33a7bc113ae8,"{""user_query"": ""How's my form?""}","{""answer"": ""Bar path shifts forward and backwa...",variance-test-baseline-0e00f0d1,2,"{""answer"": ""Pretty solid start — you’re contro...","{""inputs"": {""user_query"": ""How's my form?""}, ""...",success,NaN,12.797435,8769,0.023502,0.5,1.0
2,1356d8bf-56fd-4340-a5c6-33a7bc113ae8,"{""user_query"": ""How's my form?""}","{""answer"": ""Bar path shifts forward and backwa...",variance-test-baseline-0e00f0d1,3,"{""answer"": ""Nice work — this looks like a soli...","{""inputs"": {""user_query"": ""How's my form?""}, ""...",success,NaN,15.896458,9654,0.027175,0.5,1.0
3,17c63e2c-303e-4e78-a817-a80eb3d6a9cf,"{""user_query"": ""How do I look?""}","{""answer"": ""Elbows flare a bit on the descent ...",variance-test-baseline-0e00f0d1,1,"{""answer"": ""You look solid overall — controlle...","{""inputs"": {""user_query"": ""How do I look?""}, ""...",success,NaN,13.891332,9387,0.026274,1.0,1.0
4,17c63e2c-303e-4e78-a817-a80eb3d6a9cf,"{""user_query"": ""How do I look?""}","{""answer"": ""Elbows flare a bit on the descent ...",variance-test-baseline-0e00f0d1,2,"{""answer"": ""You look solid overall — controlle...","{""inputs"": {""user_query"": ""How do I look?""}, ""...",success,NaN,12.228618,9163,0.024532,1.0,0.5

In [4]:
test_1["correctness"]

0     1.0
1     0.5
2     0.5
3     1.0
4     1.0
5     0.5
6     0.5
7     1.0
8     1.0
9     0.5
10    1.0
11    0.5
12    NaN
13    0.5
14    0.5
Name: correctness, dtype: float64

In [5]:
test_1["hallucination"]

0     1.0
1     1.0
2     1.0
3     1.0
4     0.5
5     1.0
6     0.5
7     0.5
8     0.5
9     1.0
10    0.5
11    1.0
12    NaN
13    0.5
14    1.0
Name: hallucination, dtype: float64

In [6]:
test_1 = test_1.drop(index=12)

In [7]:
test_1 = test_1.dropna(subset=["correctness", "hallucination"])

In [8]:
test_1.isna().sum()

id                    0
inputs                0
reference_outputs     0
session_name          0
repetition            0
outputs               0
run                   0
status                0
error                14
latency               0
tokens                0
total_cost            0
correctness           0
hallucination         0
dtype: int64

In [9]:
result = compute_bootstrap(test_1, "hallucination")
print_result = print_bootstrap_results(result, "test_1", "hallucination")
hallucination_score = get_score(test_1, "hallucination")

# correctness

result = compute_bootstrap(test_1, "correctness")
print_result = print_bootstrap_results(result, "test_1", "correctness")
correctness_score = get_score(test_1, "correctness")

--- test_1: hallucination ---
95% CI Low: 1.2857142857142858
95% CI High: 1.7857142857142858
Standard error: 0.13144395542846163
MOE: 0.50
--- test_1: correctness ---
95% CI Low: 1.2142857142857142
95% CI High: 1.7142857142857142
Standard error: 0.13192351788746937
MOE: 0.50

In [10]:
test_2 = pd.read_csv("/Users/chandlershortlidge/Desktop/Ironhack/fitness-form-coach/llm-evals/variance_test_data/test02-variance-test-temp-fix.csv")
test_2.head()

,id,inputs,reference_outputs,session_name,repetition,outputs,run,status,error,latency,tokens,total_cost,correctness,hallucination
0,1356d8bf-56fd-4340-a5c6-33a7bc113ae8,"{""user_query"": ""How's my form?""}","{""answer"": ""Bar path shifts forward and backwa...",variance-test-temp-fix-09a99031,1,"{""answer"": ""Pretty solid start — your reps loo...","{""inputs"": {""user_query"": ""How's my form?""}, ""...",success,NaN,13.626086,9201,0.024712,0.5,1.0
1,1356d8bf-56fd-4340-a5c6-33a7bc113ae8,"{""user_query"": ""How's my form?""}","{""answer"": ""Bar path shifts forward and backwa...",variance-test-temp-fix-09a99031,2,"{""answer"": ""Overall: solid beginner-to-interme...","{""inputs"": {""user_query"": ""How's my form?""}, ""...",success,NaN,16.073507,9360,0.024882,0.5,1.0
2,1356d8bf-56fd-4340-a5c6-33a7bc113ae8,"{""user_query"": ""How's my form?""}","{""answer"": ""Bar path shifts forward and backwa...",variance-test-temp-fix-09a99031,3,"{""answer"": ""Pretty solid overall — you’re gett...","{""inputs"": {""user_query"": ""How's my form?""}, ""...",success,NaN,15.756722,9413,0.025496,0.5,0.5
3,17c63e2c-303e-4e78-a817-a80eb3d6a9cf,"{""user_query"": ""How do I look?""}","{""answer"": ""Elbows flare a bit on the descent ...",variance-test-temp-fix-09a99031,1,"{""answer"": ""You look solid overall — controlle...","{""inputs"": {""user_query"": ""How do I look?""}, ""...",success,NaN,15.112943,9350,0.025909,1.0,1.0
4,17c63e2c-303e-4e78-a817-a80eb3d6a9cf,"{""user_query"": ""How do I look?""}","{""answer"": ""Elbows flare a bit on the descent ...",variance-test-temp-fix-09a99031,2,"{""answer"": ""You look solid overall — controlle...","{""inputs"": {""user_query"": ""How do I look?""}, ""...",success,NaN,12.803273,9129,0.011294,1.0,1.0

In [11]:
test_2 = test_2.drop(index=12)

In [12]:
print(test_2.isna().sum())

id                    0
inputs                0
reference_outputs     0
session_name          0
repetition            0
outputs               0
run                   0
status                0
error                14
latency               0
tokens                0
total_cost            0
correctness           0
hallucination         0
dtype: int64

In [13]:
result = compute_bootstrap(test_2, "hallucination")
print_result = print_bootstrap_results(result, "test_2", "hallucination")
hallucination_score = get_score(test_2, "hallucination")

# correctness

result = compute_bootstrap(test_2, "correctness")
print_result = print_bootstrap_results(result, "test_2", "correctness")
correctness_score = get_score(test_2, "correctness")

--- test_2: hallucination ---
95% CI Low: 1.5
95% CI High: 1.9285714285714286
Standard error: 0.1106011054949675
MOE: 0.43
--- test_2: correctness ---
95% CI Low: 1.2142857142857142
95% CI High: 1.7857142857142858
Standard error: 0.1333302960202688
MOE: 0.57

In [14]:
t_test_result = do_t_test(test_1, test_2, "hallucination")

t_test_result

# P > 0.05, not statisticly siginificant

TtestResult(statistic=np.float64(-1.1465630124738169), pvalue=np.float64(0.27222832456301543), df=np.int64(13))